austinj@AustinJ-Ubuntu:~$ cd V-REP_PRO_EDU_V3_5_0_Linux/
austinj@AustinJ-Ubuntu:~/V-REP_PRO_EDU_V3_5_0_Linux$ ./vrep.sh
Using the default Lua library.
Loaded the video compression library.
Add-on script 'vrepAddOnScript-addOnScriptDemo.lua' was loaded.
Simulator launched.
Plugin 'MeshCalc': loading...
Plugin 'MeshCalc': load succeeded.
Plugin 'BlueZero': loading...
Plugin 'BlueZero': warning: replaced variable 'simB0'
Plugin 'BlueZero': load succeeded.
Plugin 'BubbleRob': loading...
Plugin 'BubbleRob': load succeeded.
Plugin 'Bwf': loading...
Plugin 'Bwf': load succeeded.
Plugin 'Collada': loading...
Plugin 'Collada': load succeeded.
Plugin 'ConvexDecompose': loading...
Plugin 'ConvexDecompose': load succeeded.
Plugin 'CustomUI': loading...
Plugin 'CustomUI': warning: replaced variable 'simUI'
Plugin 'CustomUI': load succeeded.
Plugin 'DynamicsBullet-2-78': loading...
Plugin 'DynamicsBullet-2-78': load succeeded.
Plugin 'DynamicsBullet-2-83': loading...
Plugin 'DynamicsBullet-2-83': load succeeded.
Plugin 'DynamicsNewton': loading...
Plugin 'DynamicsNewton': load succeeded.
Plugin 'DynamicsOde': loading...
Plugin 'DynamicsOde': load succeeded.
Plugin 'DynamicsVortex': loading...
Plugin 'DynamicsVortex': load succeeded.
Plugin 'ExternalRenderer': loading...
Plugin 'ExternalRenderer': load succeeded.
Plugin 'ICP': loading...
Plugin 'ICP': warning: replaced variable 'simICP'
Plugin 'ICP': load succeeded.
Plugin 'Image': loading...
Error with plugin 'Image': load failed (could not load). The plugin probably couldn't load dependency libraries. For additional infos, modify the script 'libLoadErrorCheck.sh', run it and inspect the output.
Plugin 'K3': loading...
Plugin 'K3': load succeeded.
Plugin 'LuaCommander': loading...
Plugin 'LuaCommander': warning: replaced variable 'simLuaComm'
Plugin 'LuaCommander': load succeeded.
Plugin 'LuaRemoteApiClient': loading...
Plugin 'LuaRemoteApiClient': load succeeded.
Plugin 'Mtb': loading...
Plugin 'Mtb': load succeeded.
Plugin 'OMPL': loading...
Plugin 'OMPL': warning: replaced variable 'simOMPL'
Plugin 'OMPL': load succeeded.
Plugin 'OpenMesh': loading...
Plugin 'OpenMesh': load succeeded.
Plugin 'PovRay': loading...
Plugin 'PovRay': load succeeded.
Plugin 'Qhull': loading...
Plugin 'Qhull': load succeeded.
Plugin 'RRS1': loading...
Plugin 'RRS1': load succeeded.
Plugin 'ReflexxesTypeII': loading...
Plugin 'ReflexxesTypeII': load succeeded.
Plugin 'RemoteApi': loading...
Starting a remote API server on port 19997
Plugin 'RemoteApi': load succeeded.
Plugin 'RosInterface': loading...
Plugin 'RosInterface': warning: replaced variable 'simROS'
Plugin 'RosInterface': load succeeded.
Plugin 'SDF': loading...
Plugin 'SDF': warning: replaced variable 'simSDF'
Plugin 'SDF': load succeeded.
Plugin 'SurfaceReconstruction': loading...
Plugin 'SurfaceReconstruction': warning: replaced variable 'simSurfRec'
Plugin 'SurfaceReconstruction': load succeeded.
Plugin 'Urdf': loading...
Plugin 'Urdf': load succeeded.
Plugin 'Vision': loading...
Plugin 'Vision': load succeeded.
Using the 'MeshCalc' plugin.
Initializing the Bullet physics engine in plugin 'DynamicsBullet_2_78'...
Engine version: 2.78
Plugin version: 10
Initialization successful.
Connecting to client...
Failed to connect to client.
[dummyNode] {main} DEBUG: Initialization...
[dummyNode] {main} DEBUG: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[dummyNode] {main} TRACE: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[dummyNode] {main} TRACE: ServiceClient(resolv): Announcing node 'dummyNode' to resolver...
[dummyNode] {main} TRACE: ServiceClient(resolv): Waiting for response from resolver...
[dummyNode] {main} TRACE: ServiceClient(resolv): Proxy's XPUB socket address: tcp://AustinJ-Ubuntu:56535
[dummyNode] {main} TRACE: ServiceClient(resolv): Proxy's XSUB socket address: tcp://AustinJ-Ubuntu:45495
[dummyNode] {main} TRACE: Publisher(log): Connecting to tcp://AustinJ-Ubuntu:45495...
[dummyNode] {main} TRACE: Starting heartbeat thread...
[dummyNode] {main} DEBUG: Initializing sockets...
[Skipped logger because in another thread]: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[dummyNode] {main} DEBUG: Initialization complete.
[Skipped logger because in another thread]: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[dummyNode] {main} DEBUG: Killing heartbeat thread...
[dummyNode] {main} DEBUG: Cleanup sockets...
[dummyNode] {main} TRACE: ServiceClient(resolv): Disconnecting from tcp://localhost:22000...
[dummyNode] {main} DEBUG: Initialization...
[dummyNode] {main} DEBUG: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[dummyNode] {main} TRACE: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[dummyNode] {main} TRACE: ServiceClient(resolv): Announcing node 'dummyNode' to resolver...
[dummyNode] {main} TRACE: ServiceClient(resolv): Waiting for response from resolver...
[dummyNode] {main} TRACE: ServiceClient(resolv): Proxy's XPUB socket address: tcp://AustinJ-Ubuntu:56535
[dummyNode] {main} TRACE: ServiceClient(resolv): Proxy's XSUB socket address: tcp://AustinJ-Ubuntu:45495
[dummyNode] {main} TRACE: Publisher(log): Connecting to tcp://AustinJ-Ubuntu:45495...
[dummyNode] {main} TRACE: Starting heartbeat thread...
[dummyNode] {main} DEBUG: Initializing sockets...
[dummyNode] {main} DEBUG: Initialization complete.
[Skipped logger because in another thread]: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[Skipped logger because in another thread]: ServiceClient(resolv): Connecting to tcp://localhost:22000...
rosBubbleRob2 just started with node name rosBubbleRob10657398
rosBubbleRob2 just ended!
[dummyNode] {main} DEBUG: Killing heartbeat thread...
[dummyNode] {main} DEBUG: Cleanup sockets...
[dummyNode] {main} TRACE: ServiceClient(resolv): Disconnecting from tcp://localhost:22000...
[b0Node] {main} DEBUG: Initialization...
[b0Node] {main} DEBUG: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[b0Node] {main} TRACE: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[b0Node] {main} TRACE: ServiceClient(resolv): Announcing node 'b0Node' to resolver...
[b0Node] {main} TRACE: ServiceClient(resolv): Waiting for response from resolver...
[b0Node] {main} TRACE: ServiceClient(resolv): Proxy's XPUB socket address: tcp://AustinJ-Ubuntu:56535
[b0Node] {main} TRACE: ServiceClient(resolv): Proxy's XSUB socket address: tcp://AustinJ-Ubuntu:45495
[b0Node] {main} TRACE: Publisher(log): Connecting to tcp://AustinJ-Ubuntu:45495...
[b0Node] {main} TRACE: Starting heartbeat thread...
[b0Node] {main} DEBUG: Initializing sockets...
[b0Node] {main} TRACE: Publisher(sensorTrigger205643): Connecting to tcp://AustinJ-Ubuntu:45495...
[Skipped logger because in another thread]: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[Skipped logger because in another thread]: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[b0Node] {main} TRACE: Publisher(simTime205643): Connecting to tcp://AustinJ-Ubuntu:45495...
[b0Node] {main} TRACE: Subscriber(rightMotorSpeed205643): Connecting to tcp://AustinJ-Ubuntu:56535...
[b0Node] {main} TRACE: Subscriber(leftMotorSpeed205643): Connecting to tcp://AustinJ-Ubuntu:56535...
[b0Node] {main} TRACE: Publisher(pauseFlag205643): Connecting to tcp://AustinJ-Ubuntu:45495...
[b0Node] {main} DEBUG: Initialization complete.
[b0_bubbleRob] {main} DEBUG: Initialization...
[b0_bubbleRob] {main} DEBUG: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[b0_bubbleRob] {main} TRACE: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[b0_bubbleRob] {main} TRACE: ServiceClient(resolv): Announcing node 'b0_bubbleRob' to resolver...
[b0_bubbleRob] {main} TRACE: ServiceClient(resolv): Waiting for response from resolver...
[b0_bubbleRob] {main} TRACE: ServiceClient(resolv): Proxy's XPUB socket address: tcp://AustinJ-Ubuntu:56535
[b0_bubbleRob] {main} TRACE: ServiceClient(resolv): Proxy's XSUB socket address: tcp://AustinJ-Ubuntu:45495
[b0_bubbleRob] {main} TRACE: Publisher(log): Connecting to tcp://AustinJ-Ubuntu:45495...
[b0_bubbleRob] {main} TRACE: Starting heartbeat thread...
[b0_bubbleRob] {main} DEBUG: Initializing sockets...
[b0_bubbleRob] {main} TRACE: Publisher(leftMotorSpeed205643): Connecting to tcp://AustinJ-Ubuntu:45495...
[Skipped logger because in another thread]: ServiceClient(resolv): Skipping resolution because remote address (tcp://localhost:22000) was given
[Skipped logger because in another thread]: ServiceClient(resolv): Connecting to tcp://localhost:22000...
[b0_bubbleRob] {main} TRACE: Publisher(rightMotorSpeed205643): Connecting to tcp://AustinJ-Ubuntu:45495...
[b0_bubbleRob] {main} TRACE: Subscriber(sensorTrigger205643): Connecting to tcp://AustinJ-Ubuntu:56535...
[b0_bubbleRob] {main} TRACE: Subscriber(simTime205643): Connecting to tcp://AustinJ-Ubuntu:56535...
[b0_bubbleRob] {main} TRACE: Subscriber(pauseFlag205643): Connecting to tcp://AustinJ-Ubuntu:56535...
[b0_bubbleRob] {main} DEBUG: Initialization complete.
[b0_bubbleRob] {main} DEBUG: Killing heartbeat thread...
[b0_bubbleRob] {main} DEBUG: Cleanup sockets...
[b0_bubbleRob] {main} TRACE: Publisher(leftMotorSpeed205643): Disconnecting from tcp://AustinJ-Ubuntu:45495...
[b0_bubbleRob] {main} TRACE: Publisher(rightMotorSpeed205643): Disconnecting from tcp://AustinJ-Ubuntu:45495...
[b0_bubbleRob] {main} TRACE: Subscriber(sensorTrigger205643): Disconnecting from tcp://AustinJ-Ubuntu:56535...
[b0_bubbleRob] {main} TRACE: Subscriber(simTime205643): Disconnecting from tcp://AustinJ-Ubuntu:56535...
[b0_bubbleRob] {main} TRACE: Subscriber(pauseFlag205643): Disconnecting from tcp://AustinJ-Ubuntu:56535...
[b0_bubbleRob] {main} TRACE: ServiceClient(resolv): Disconnecting from tcp://localhost:22000...
